name: pluto_menu_bar
description: A menu bar for flutter. You can add as many submenus as you want, and you can change the default style.
version: 3.0.1
homepage: https://pluto.weblaze.dev
repository: https://github.com/bosskmk/pluto_menu_bar

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  pointer_interceptor: ^0.9.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_lints: ^2.0.1
